[RunSvc]
JobName = "tray_basic_setup"
BeamType = "IAEA"
PhspInputFileName = "/mnt/d/Data/mc/phsp/Clinac2300-PhSp-Primo/TNSIM157_10x10s2-f0" # AGH JH File
PhspEvtVrtxMultiplicityTreshold = 10
PrintProgressFrequency = 0.01
GenerateCT = false
PrimariesAnalysis = false
NTupleAnalysis = true
RunAnalysis = true

[GeoSvc]
BuildLinac = true
BuildPatient = false

[Parts]
#[Name, Position, Rotation, Material, STL_File]
elements = [
["PlaceholderName1", [0.0, 0.0, 0.0], [0.0, 0.0, 0.0], "G4_WATER", "/mnt/c/Users/Jakub/Desktop/gear_detector.obj"],
["PlaceholderName2", [0.0, 0.0, 0.0], [0.0, 0.0, 0.0], "G4_WATER", "/mnt/c/Users/Jakub/Desktop/gear_detector.obj"],
["PlaceholderName3", [0.0, 0.0, 0.0], [0.0, 0.0, 0.0], "G4_WATER", "/mnt/c/Users/Jakub/Desktop/gear_detector.obj"],
["PlaceholderName4", [0.0, 0.0, 0.0], [0.0, 0.0, 0.0], "G4_WATER", "/mnt/c/Users/Jakub/Desktop/gear_detector.obj"],
["PlaceholderName5", [0.0, 0.0, 0.0], [0.0, 0.0, 0.0], "G4_WATER", "/mnt/c/Users/Jakub/Desktop/gear_detector.obj"],
["PlaceholderName6", [0.0, 0.0, 0.0], [0.0, 0.0, 0.0], "G4_WATER", "/mnt/c/Users/Jakub/Desktop/gear_detector.obj"],
["PlaceholderName7", [0.0, 0.0, 0.0], [0.0, 0.0, 0.0], "G4_WATER", "/mnt/c/Users/Jakub/Desktop/gear_detector.obj"],
["PlaceholderName8", [0.0, 0.0, 0.0], [0.0, 0.0, 0.0], "G4_WATER", "/mnt/c/Users/Jakub/Desktop/gear_detector.obj"],
["PlaceholderName9", [0.0, 0.0, 0.0], [0.0, 0.0, 0.0], "G4_WATER", "/mnt/c/Users/Jakub/Desktop/gear_detector.obj"]
]


[RunSvc_Plan] 
PlanInputFile = [
    "plan/custom/rot00deg_0.1x320.dat"
]

