[RunSvc]
JobName = "tray_basic_setup"
BeamType = "IAEA"
PhspInputFileName = "/mnt/d/Data/mc/phsp/Clinac2300-PhSp-Primo/TNSIM157_10x10s2-f0" # AGH JH File
PhspEvtVrtxMultiplicityTreshold = 10
PrintProgressFrequency = 0.01
GenerateCT = false
PrimariesAnalysis = false
NTupleAnalysis = true
RunAnalysis = true

[GeoSvc]
BuildLinac = true
BuildPatient = false

[Parts]
#[Name, Position, Rotation, Material, STL_File]
elements = [
["Spur001", [0.0, 0.0, 0.0], [0.0, 0.0, 0.0], "G4_WATER", "/mnt/wsl/Alma/home/jackie/work/impress_U/geometryWrapper/utils/../output/stl/Spur001.stl"],
["Spur002", [0.0, 0.0, 0.0], [0.0, 0.0, 0.0], "G4_WATER", "/mnt/wsl/Alma/home/jackie/work/impress_U/geometryWrapper/utils/../output/stl/Spur002.stl"],
["Spur003", [0.0, 0.0, 0.0], [0.0, 0.0, 0.0], "G4_WATER", "/mnt/wsl/Alma/home/jackie/work/impress_U/geometryWrapper/utils/../output/stl/Spur003.stl"]
]


[RunSvc_Plan] 
PlanInputFile = [
    "plan/custom/rot00deg_0.1x320.dat"
]

