[RunSvc]
JobName = "tray_basic_setup"
BeamType = "IAEA"
# PhspInputFileName = "/mnt/c/Users/brachwal-agh/Workspace/IAEA/Clinac2300-PhSp-Primo/TNSIM157_3x3s2-f0" # AGH Dell-XPS location
# PhspInputFileName = "/etude/brachwal/iaea-phsp/TNSIM157_3x3s2-f0" # AGH LHCBD2 location
# PhspInputFileName = "/mnt/e/Data/dose3d/mc/phsp/Clinac2300-PhSp-Primo/TNSIM157_3x3s2-f0" # AGH BR location
PhspInputFileName = "/mnt/e/Data/dose3d/mc/phsp/Clinac2300-PhSp-Primo/TNSIM157_10x10s2-f0" # AGH BR location
# PhspInputFileName = "/mnt/d/Data/mc/phsp/Clinac2300-PhSp-Primo/TNSIM157_10x10s2-f0" # AGH JH File
# PhspInputFileName = "/mnt/e/phsp/TNSIM157_3x3s2-f0" # AGH JH Home File
PhspEvtVrtxMultiplicityTreshold = 10
PrintProgressFrequency = 0.01
GenerateCT = false
PrimariesAnalysis = false
NTupleAnalysis = true
RunAnalysis = true

[GeoSvc]
BuildLinac = false
BuildPatient = false

[Parts]
#[Name, Position, Rotation, Material, STL_File]
elements = [
["gear001", [0.0, 0.0, 0.0], [0.0, 0.0, 0.0], "G4_WATER", "/home/jackie/work/impress_U/geometryWrapper/utils/../output/stl/gear001.stl"],
["Spur001", [0.0, 0.0, 0.0], [0.0, 0.0, 0.0], "G4_WATER", "/home/jackie/work/impress_U/geometryWrapper/utils/../output/stl/Spur001.stl"],
["_1", [0.0, 0.0, 0.0], [0.0, 0.0, 0.0], "G4_WATER", "/home/jackie/work/impress_U/geometryWrapper/utils/../output/stl/_1.stl"],
["Spur002", [0.0, 0.0, 0.0], [0.0, 0.0, 0.0], "G4_WATER", "/home/jackie/work/impress_U/geometryWrapper/utils/../output/stl/Spur002.stl"],
["_2", [0.0, 0.0, 0.0], [0.0, 0.0, 0.0], "G4_WATER", "/home/jackie/work/impress_U/geometryWrapper/utils/../output/stl/_2.stl"],
["Spur003", [0.0, 0.0, 0.0], [0.0, 0.0, 0.0], "G4_WATER", "/home/jackie/work/impress_U/geometryWrapper/utils/../output/stl/Spur003.stl"],
["Spur004", [0.0, 0.0, 0.0], [0.0, 0.0, 0.0], "G4_WATER", "/home/jackie/work/impress_U/geometryWrapper/utils/../output/stl/Spur004.stl"],
["Shell", [0.0, 0.0, 0.0], [0.0, 0.0, 0.0], "G4_WATER", "/home/jackie/work/impress_U/geometryWrapper/utils/../output/stl/Shell.stl"],
["gearL", [0.0, 0.0, 0.0], [0.0, 0.0, 0.0], "G4_WATER", "/home/jackie/work/impress_U/geometryWrapper/utils/../output/stl/gearL.stl"]
]


[RunSvc_Plan] 
PlanInputFile = [
    "plan/custom/rot00deg_0.1x320.dat"
]

