[RunSvc]
JobName = "tray_basic_setup"
BeamType = "IAEA"
# PhspInputFileName = "/mnt/c/Users/brachwal-agh/Workspace/IAEA/Clinac2300-PhSp-Primo/TNSIM157_3x3s2-f0" # AGH Dell-XPS location
# PhspInputFileName = "/etude/brachwal/iaea-phsp/TNSIM157_3x3s2-f0" # AGH LHCBD2 location
# PhspInputFileName = "/mnt/e/Data/dose3d/mc/phsp/Clinac2300-PhSp-Primo/TNSIM157_3x3s2-f0" # AGH BR location
PhspInputFileName = "/mnt/e/Data/dose3d/mc/phsp/Clinac2300-PhSp-Primo/TNSIM157_10x10s2-f0" # AGH BR location
# PhspInputFileName = "/mnt/d/Data/mc/phsp/Clinac2300-PhSp-Primo/TNSIM157_10x10s2-f0" # AGH JH File
# PhspInputFileName = "/mnt/e/phsp/TNSIM157_3x3s2-f0" # AGH JH Home File
PhspEvtVrtxMultiplicityTreshold = 10
PrintProgressFrequency = 0.05
GenerateCT = false
PrimariesAnalysis = false
NTupleAnalysis = true
RunAnalysis = true

[GeoSvc]
BuildLinac = true
BuildPatient = false

[PatientGeometry]
Type = "D3DDetector"
EnviromentPositionX = 0.0
EnviromentPositionY = 0.0
EnviromentPositionZ = 0.0
EnviromentSizeX = 30.0
EnviromentSizeY = 30.0
EnviromentSizeZ = 30.0
EnviromentMedium = "Usr_G4AIR20C"

[D3DDetector_Detector]
TopPositionInEnv = [0.0,0.0,-9.8] # In mm
Voxelization = [2,2,2] # Number of cels in every direction

[D3DDetector_Layer]
MRowShift = false
MLayerShift = false

[D3DDetector_Cell]
Medium = "Usr_G4AIR20C"
Voxelization = [2,2,2]
TracksAnalysis = false
CellVoxelisedScorer = true

[Tray001]
Rotation = [0.0, 180.0, 0.0] # in deg
Position = [-390.0, 390.0, 0.0] # relative to global (0,0,0)
CellVoxelization = [2,2,2]

[RunSvc_Plan] # paths can be relative (to PROJECT_DATA) or absolute
# PlanInputFile = [
#     "plan/custom/rot00deg_10x10.dat"
# ]
nControlPoints = 1
BeamRotation = [0.0] # Per Control Point
nParticles = [1e3] # Per Control Point
FieldMask = [
    {Type = "Elipsoidal", SizeA = 25.0, SizeB = 25.0 }
]
