[RunSvc]
JobName = "STL test"
BeamType = "gps"
GpsMacFileName = "/home/geant4/impress-u-agh/simulation-platform/scripts/gps/gps_mono_gammas_pre.mac"
PhspEvtVrtxMultiplicityTreshold = 32
PrintProgressFrequency = 0.005
GenerateCT = false
PrimariesAnalysis = false
NTupleAnalysis = false
RunAnalysis = true

[GeoSvc]
BuildLinac = true
BuildPatient = true

[PatientGeometry]
Type = "D3DDetector"
EnviromentPositionX = 0.0
EnviromentPositionY = 0.0
EnviromentPositionZ = 0.0
EnviromentSizeX = 2000.0
EnviromentSizeY = 2000.0
EnviromentSizeZ = 2000.0
EnviromentMedium = "G4_WATER"

[D3DDetector_Detector]
TopPositionInEnv = [-50.0,0.0,0.0] # In mm
Geomertry = "gear001.stl"

[D3DDetector_Layer]
Positioning = "dose3d/geo/Tray/single_tray.csv"


[D3DDetector_Cell]
Medium = "RMPS470" #G4_WATER, PMMA
Voxelization = [2,2,2]

[RunSvc_Plan] 
PlanInputFile = [
    "plan/custom/rot00deg_0.1x320.dat"
]

