[RunSvc]
JobName = "web_job_example"
BeamType = "gps" 
NTupleAnalysis = true 
FieldShape = "Elipsoidal"
FieldSizeA = 10 # mm
FieldSizeB = 30 # mm

[PatientGeometry]
Type = "D3DDetector"
EnviromentSizeX = 50.0
EnviromentSizeY = 50.0
EnviromentSizeZ = 80.0
EnviromentMedium = "G4_Galactic"

[D3DDetector_Detector]
TopPositionInEnv = [0.0,0.0,-25.0] # In mm
Voxelization = [3,2,5] # Number of cels in every direction

[D3DDetector_Cell]
Medium = "RMPS470" #G4_WATER, PMMA
Voxelization = [5,5,5]
TracksAnalysis = false
# CellScorer = false
# CellVoxelisedScorer = true

[RunSvc_Plan]
Control_Points_In_Treatment_Plan = 1
Gantry_Angle_Per_Control_Point = [0.0]
Particle_Counter_Per_Control_Point = [1e5]

